export const actionIds = {
  FETCH_MEMBERS_REQUEST: 'FETCH_MEMBERS_REQUEST' as const,
  FETCH_MEMBERS_SUCCESS: 'FETCH_MEMBERS_SUCCESS' as const,
  FETCH_MEMBERS_ERROR: 'FETCH_MEMBERS_ERROR' as const,
};
